### PR TITLE
Add support for Katakana-mode to in T-Code

### PR DESCRIPTION
**Pull request by 0x005c**
Generally, Katakana-mode isn't needed in T-Code.
Because T-Code provides direct 2-strokes set for Katakana.
Users can use them to input Katakana.

If we add support for Katakana-mode, users just remember 2-strokes set for Hiragana to input Katakana.

## How to reproduce
1. set code table file of tut-code to `tcode.scm`
1. restart uim
1. switch input method to tut-code
1. switch to katakana mode
1. type `yf`
1. `あ` will appear (this is Hiragana, but Katakana `ア` is expected)

### CODE REVIEW

**Comment by kou** [comment]
I'm not sure Katakana-mode is meaningful in T-Code context.
T-Code maps a 2-strokes to a character without distinction between Hiragana and Katakana.
(Why is `;w` not used for `ア`?)

**Comment by 0x005c** [comment]
Yes, Katakana-mode is not useful for users that remembers all mapped strokes for Katakana.
But some users who is new to T-Code (includes me) cannot type all Katakana directly, and Katakana-mode is useful for them.
We already have postfix Katakana conversion, but it will be more convenient with Katakana-mode.

**Comment by kou** [comment]
OK.
Did you confirm that this doesn't break backward compatibility? If this doesn't break backward compatibility for normal use, we'll merge this.

**Comment by 0x005c** [comment]
As far as I checked, this change does not break backward compatibility in Direct input mode, Hiragana mode, and Kigou mode.
If you mean that the behaviour of Katakana mode should not be changed by default,
I have to add option to switch between old behaviour and new behaviour.

**Comment by kou** [comment]
Thanks.
The current Katakana-mode doesn't work, right?
Then nobody uses the current Katakana-mode. We don't need to care about the current Katakana-mode.

**Pull request merged**
