### PR TITLE
fixes a bug that causes the wsl command to hang on uim-fep

### PR DESCRIPTION
**Pull request by yamam**
The wsl command hangs on uim-fep.

$ uim-fep -e /mnt/c/windows/system32/cmd.exe /c dir

The cause of the hang is unknown, but could be fixed by writing the input data to the pty at once.

### CODE REVIEW

**Comment by kou** [comment]
Does `strace` work on WSL? Could you try getting information for debug?

```bash
strace uim-fep -e /mnt/c/windows/system32/cmd.exe /c dir
```

**Comment by yamam** [comment]
[strace-hang.txt](https://github.com/uim/uim/files/4978813/strace-hang.txt)
[strace-fix.txt](https://github.com/uim/uim/files/4978716/strace-fix.txt)

Line 1362 of strace-fix.txt writes the escape sequence 'ESC[24;1R'.
The details of this escape sequence are unknown, but 24 and 1 refer to the row and column of the terminal cursor.
On the strace-hang.txt side, this escape sequence is broken and hangs in the subsequent select.

**Comment by yamam** [comment]
[strace-f-hang.txt](https://github.com/uim/uim/files/4978824/strace-f-hang.txt)
[strace-f-fix.txt](https://github.com/uim/uim/files/4978825/strace-f-fix.txt)

Sorry, I forgot to add the -f option to the strace.

**Comment by kou** [comment]
Thanks.
It seems that `cmd.exe` requires inputting whole escape sequence at once.

I'll merge this with some adjustments.

**Comment by yamam** [comment]
Thank you for merging.
I noticed that the title is not accurate.
To be precise, fixes a bug that causes the windows command to hang on uim-fep on WSL.

**Pull request merged**
